CI updates - Sun Nov  6 07:55:02 AM CST 2022

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,77 +6,103 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
+  # build:
+  #   runs-on: ubuntu-latest
 
+  #   strategy:
+  #     matrix:
+  #       target:
+  #         - i686-unknown-linux-gnu
+  #         - i686-pc-windows-gnu
+  #         - aarch64-unknown-linux-gnu
+
+  #         # https://github.com/cross-rs/cross-toolchains#apple-targets
+  #         # - x86_64-apple-darwin
+  #         # - aarch64-apple-darwin
+
+  #   steps:
+  #     - name: Check out code
+  #       uses: actions/checkout@v3
+
+  #     - name: Install rustup
+  #       run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+
+  #     - name: Install cross
+  #       run: cargo install -f cross
+
+  #     - name: Run tests
+  #       run: cross test
+
+  #     - name: Build release executable
+  #       run: cross build --target ${{ matrix.target }} --release
+
+  #     - name: Build release package
+  #       run: |
+  #         export SUFFIX=$(echo '${{ matrix.target }}' |grep -q '\-windows-' && echo '.exe')
+  #         export ARCH=$(echo '${{ matrix.target }}' |cut -d - -f 1)
+  #         export OS=$(echo '${{ matrix.target }}' |cut -d - -f 3)
+  #         export RELEASE=portr-${OS}-${ARCH}-r${{ github.run_number }}
+  #         export BIN=target/${{ matrix.target }}/release/portr${SUFFIX}
+  #         ls -l $BIN || exit 1
+  #         mkdir $RELEASE || exit 1
+  #         cp $BIN $RELEASE/ || exit 1
+  #         cp LICENSE README.md portr.toml.example $RELEASE/ || exit 1
+  #         ls -l $RELEASE/* || exit 1
+  #         zip -r ${RELEASE}.zip $RELEASE/ || exit 1
+
+  #     - name: List packages
+  #       run: ls -lh *.zip
+
+  #     - name: Upload package artifact
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: zips
+  #         path: portr-*.zip
+
+  mac-build:
+    runs-on: macos-12
     strategy:
       matrix:
         target:
-          - i686-unknown-linux-gnu
-          - i686-pc-windows-gnu
-          - aarch64-unknown-linux-gnu
-
-          # https://github.com/cross-rs/cross-toolchains#apple-targets
-          # - x86_64-apple-darwin
-          # - aarch64-apple-darwin
+          - aarch64-apple-darwin
 
     steps:
       - name: Check out code
         uses: actions/checkout@v3
 
-      - name: Install rustup
-        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+      - name: Install toolchain
+        run: rustup toolchain install nightly -t ${{ matrix.target }}
 
-      - name: Install cross
-        run: cargo install -f cross
+      - name: Add target
+        run: rustup target add ${{ matrix.target }}
 
-      - name: Run tests
-        run: cross test
+      - name: Build release executable
+        run: cargo build --target ${{ matrix.target }} --release
 
       - name: Build release executable
         run: cross build --target ${{ matrix.target }} --release
 
-      - name: Build release package
-        run: |
-          export SUFFIX=$(echo '${{ matrix.target }}' |grep -q '\-windows-' && echo '.exe')
-          export ARCH=$(echo '${{ matrix.target }}' |cut -d - -f 1)
-          export OS=$(echo '${{ matrix.target }}' |cut -d - -f 3)
-          export RELEASE=portr-${OS}-${ARCH}-r${{ github.run_number }}
-          export BIN=target/${{ matrix.target }}/release/portr${SUFFIX}
-          ls -l $BIN || exit 1
-          mkdir $RELEASE || exit 1
-          cp $BIN $RELEASE/ || exit 1
-          cp LICENSE README.md portr.toml.example $RELEASE/ || exit 1
-          ls -l $RELEASE/* || exit 1
-          zip -r ${RELEASE}.zip $RELEASE/ || exit 1
+      # - name: Run tests
+      #   run: cargo test
 
-      - name: List packages
-        run: ls -lh *.zip
+  # release:
+  #   runs-on: ubuntu-latest
+  #   needs: build
+  #   steps:
+  #     - uses: actions/download-artifact@v3
+  #       with:
+  #         path: dist
 
-      - name: Upload package artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: zips
-          path: portr-*.zip
+  #     - name: List artifacts
+  #       run: find dist -type f
 
-  release:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - uses: actions/download-artifact@v3
-        with:
-          path: dist
-
-      - name: List artifacts
-        run: find dist -type f
-
-      - name: upload artifact
-        if: github.ref == 'refs/heads/main'
-        uses: softprops/action-gh-release@v1
-        with:
-          name: r${{ github.run_number }}
-          files: dist/zips/portr-*.zip
-          fail_on_unmatched_files: yes
-          draft: no
-          prerelease: no
-          tag_name: r${{ github.run_number }}
+  #     - name: upload artifact
+  #       if: github.ref == 'refs/heads/main'
+  #       uses: softprops/action-gh-release@v1
+  #       with:
+  #         name: r${{ github.run_number }}
+  #         files: dist/zips/portr-*.zip
+  #         fail_on_unmatched_files: yes
+  #         draft: no
+  #         prerelease: no
+  #         tag_name: r${{ github.run_number }}
